version: 2
executorType: docker
containerInfo:
  - image: circleci/build-image:ubuntu-14.04-XL-783-8f4b56f
stages:
  build:
    workDir: ~/BedwarsRel
    environment:
      - SHORT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    steps:
      - type: checkout

      - type: shell
        shell: /bin/bash --login
        command: mvn clean deploy --settings settings.xml

      - type: artifacts-store
        path: target/
        destination: build

