version: 2
executorType: docker
containerInfo:
  - image: ubuntu:14.04
    cmd: ["/bin/bash"] # specify if image does not already have Command set
stages:
  build:
    workDir: ~/my-project
    steps:
      - type: checkout
      # Add an entry to /etc/hosts
      - type: shell
        shell: /bin/bash --login
        command: echo "hi"

      # Save artifacts
      - type: artifacts-store
        path: /tmp/artifacts
        destination: build

      # Upload test results
      - type: test-results-store
        path: /tmp/test-results
