version: 2
executorType: docker
containerInfo:
  - image: circleci/build-image:ubuntu-14.04-XL-783-8f4b56f
stages:
  build:
    workDir: ~/BedwarsRel
    steps:
      - type: checkout

      - type: shell
        shell: /bin/bash --login
        command: mvn install

      - type: artifacts-store
        path: target/
        destination: build
