version: 2
executorType: docker
containerInfo:
  - image: circleci/build-image:ubuntu-14.04-XL-783-8f4b56f
stages:
  build:
    workDir: ~/BedwarsRel
    steps:
      - type: checkout
      
      - type: shell
        shell: /bin/bash --login
        command: SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
        
      - type: shell
        shell: /bin/bash --login
        command: |
          if [ "${CIRCLE_BRANCH}" == "master"];
            mvn clean install -P ci-release,attach-javadocs,attach-sources;
          else
            mvn clean install -P ci-snapshot,attach-javadocs,attach-sources;
          fi
        
      - type: deploy
        shell: /bin/bash --login
        command: |
          if [ "${CIRCLE_BRANCH}" == "master"];
            mvn deploy -P ci-release,deploy-release,attach-javadocs,attach-sources;
          elif [ "${CIRCLE_BRANCH}" == "develop"];
            mvn deploy -P ci-snapshot,deploy-snapshot,attach-javadocs,attach-sources;
          fi

      - type: artifacts-store
        path: target/
        destination: build

