lobbytime: 60
friendlyfire: false
bungeecord: false
ressource:
    bronze:
        spawninterval: 1000
        amount: 2
    iron:
        spawninterval: 5000
        amount: 1
    gold:
        spawninterval: 10000
        amount: 1
texts:
    gamecheck:
        LOC_NOT_SET_ERROR: Locations for the region were not set properly!
        TEAM_SIZE_LOW_ERROR: You have to set more teams!
        NO_RES_SPAWNER_ERROR: You didn't set any resource spawner!
        NO_LOBBY_SET: You didn't set a lobby!
        TEAMS_WITHOUT_SPAWNS: There are team(s) without a spawn location!
        NO_ITEMSHOP_CATEGORIES: No itemshop categories found!
shop:
    armor:
        item: DIAMOND_CHESTPLATE
        name: Rüstung
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 10
              reward:
                item: DIAMOND_SWORD
                amount: 1
                enchants:
                    KNOCKBACK: 2
                    DAMAGE_ALL: 3