################################
######## BEDWARS CONFIG ########
###### CREATED BY YANNICI ######
################################

## TYPE HELP ##
# int: number (not decimal)
# string: a normal text (in most cases you can use colorcodes with a beginning §)
# boolean: true or false (IMPORTANT: true OR false ONLY)
# list<?>: a list of type ? (? is the type of the list items)
# byte: a int but limited between -128 ... 127
# short: a int but limited between -32768 ... 32767

# Enabled Metrics
# type: boolean
# Plugin Metrics sending anonymous data about your server
# to store statistics about the bedwars plugin. This is really
# helpful for me (Yannici, the developer of bedwars). You can
# disable it anyway, that won't be a disadvantage
plugin-metrics: true

# Game length
# Type: int
# The time the game should maximum run (in minutes). When the countdown expires
# the game will end without a winner.
gamelength: 60

# Lobby Time
# Type: int
# The lobby time defines how long you have to
# wait in the lobby until the game starts (when enough players) in seconds.
lobbytime: 60

# Countdown start rule
# Type: int
# Countdown start options:
# 0 = If all teams got min. 1 player, the game start countdown starts
# 1 = If min. X (addgame parameter) players joined the game, game countdown starts
lobbycountdown-rule: 0

# Friendly Fire
# Type: boolean (true or false)
# Sets if friendlyfire is enabled (damage team mates)
friendlyfire: false

# Game over delay
# Type: int
# How much time (in seconds) should be waited until all players
# will be teleported after a game ends.
gameoverdelay: 10

# Statistic-Configuration
statistics:
    # Statistics enable
    # type: boolean
    # Set to true to enable statistics. Otherwise set to false
    enabled: false
    
    # Achievements storage type
    # type: string
    # yaml or database
    # Set to yaml to store statistics in a Yaml-Configuration file or
    # set to database to store statistics in the defined database. If no database
    # configured, the statistics will be stored in Yaml-Files
    storage: yaml
    
# Database (currently only mysql) configuration
database:

    # Database host
    # type: string
    # Hostname of your database
    host: localhost
    
    # Database port
    # type: int
    # Port of your database. Default mysql port: 3306
    port: 3306
    
    # Database name
    # type: string
    # The name of your database
    db: database
    
    # Database user
    # type: string
    # User for database authentication
    user: root
    
    # Database password
    # type: string
    # Password of database user for authentication
    password: secret
    
    # Connection-Pooling configuration (only professional use)
    # For bungeecord servers it is recommended to use lower pool sizes because
    # they have only one bedwars game per server and only need a 
    # very small amount of connections
    connection-pooling:
    
        # Min connection pool size
        # type: int
        # Defines how large the min pool size for connections should be
        # the higher the value the higher the load of the database server
        min-pool-size: 3
        
        # Max connection pool size
        # type: int
        # Defines how large the max pool size for connections should be
        # the higher the value the higher is the security that no connection locks
        # will occur. But the load of the database server will be higher when 
        # many connections are used!
        max-pool-size: 15
        
# Spectation enabled
# Type: boolean
# Defines if spectators are allowed
spectation-enabled: false

# Respawn protection
# Type: int
# The time which players are protected after respawn in seconds
# Set it to 0 to disable respawn protection.
respawn-protection: 0

# Allowed ingame commands
# type: List<String>
# Defines a list of commands which are allowed for all for default.
# Can be set with an starting / or without
allowed-commands:
    - /lobby
    - /server lobby
    - /spawn

endgame:
### Main lobby enabled
### Type: boolean
### If you want, that all players will be teleported to a specific
### location (you can set with /bw setmainlobby {game}) after a game or when a player
### uses /bw leave. If this is set to false, the player will be teleported to the location
### where he joined the game!
    mainlobby-enabled: false
    
### All players to mainlobby
### Type: boolean
### Configures if all players will be teleported to mainlobby after game
### if false, all players will be teleported back to lobby to restart
### a new game. This is only recognized if mainlobby-enabled set to true
    all-players-to-mainlobby: false 

# Bungeecord configurations
bungeecord:
### Enable Bungeecord
### Type: boolean
### Set to true to enable bungeecord compatibility. Set to false when you have
### a single server and don't use bungeecord.
    enabled: false

### Bungeecord Hubserver
### Type: string
### The name of the hub/main server of the bungeecord server-farm. This will be
### the server where the player will be teleported when they leave.
    hubserver: test

### Message of the Day configuration
### Type: string (colorcodes with §)
### Here you can specify the MOTDs which should be used
### at this bedwars server of your bungeecord server-farm.
### Useful for bedwars join signs in your lobby
    motds:
        lobby: §a[Lobby]
        running: §e[Running]
        stopped: §4[Stopped]
### Localization (language)
### Type: string (length: 2)
### Sets the localization which should be used. 
### Check the plugin description for possible languages!
### The fallback language is en (english).
locale: de

# Permissions
permissions:
### VIP can start
### Type: boolean
### Defines if VIP-Users can force start a game!
    vipCanStart: false

# Ressources config
ressource:

### Spawn Interval:
### Type: int
### The interval in milliseconds when ressource should spawn!
### Amount:
### Type: int
### The amount of items should spawn 
### when the interval spawn the ressource
    bronze:
        spawninterval: 1000
        amount: 2
    iron:
        spawninterval: 5000
        amount: 1
    gold:
        spawninterval: 10000
        amount: 1

### SHOP ###
### NOT ALLOWED CATEGORY MATERIAL: SLIME_BALL, SNOW_BALL
### The categories (unique key!)
###### Categories:
###### item:
######  type: string or int
######  Itemname or Item-ID which should be 
######  displayed to represent the category
###### name: 
######  type: string
######  Name of the category
###### lore:
######  type: list<string>
######  The lore (description) the category should have.
###### order:
######  type: int
######  The order the categories will be displayed
######### Offers:
######### item1 (first trade item):
#########  item: 
#########   type: string or int
#########   Item-Name or Item-ID
#########  amount: 
#########   type: int
#########   The stack amount the item should have
#########  name:
#########   type: string (colorcodes with §)
#########   A specific name for the item
#########  enchants:
#########   key: Has to be the enchant-ID or enchant-name!
#########   value: The level of the enchant
#########  lore:
#########   type: list<string> (colorcodes with §)
#########   The lores this item should have
#########  meta:
#########   type: short (potion) or byte (any other item)
#########   The meta byte which will be added to the item
######### item2 (optional, second trade item): See item1
######### reward (reward item): See item1
shop:
    armor:
        item: DIAMOND_CHESTPLATE
        name: Rüstung
        order: 10
        lore:
            - Protect yourself with armor! Click here.
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: LEATHER_HELMET
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: LEATHER_LEGGINGS
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: LEATHER_BOOTS
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: IRON_INGOT
                amount: 1
              reward:
                item: 303
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 303
                amount: 1
                enchants:
                    0: 2
            - item1:
                item: IRON_INGOT
                amount: 7
              reward:
                item: 303
                amount: 1
                enchants:
                    0: 3
            - item1:
                item: GOLD_INGOT
                amount: 10
              reward:
                name: Helm
                namecolor: RED
                item: 306
                amount: 1
                enchants:
                    0: 2
    swords:
        item: DIAMOND_SWORD
        name: Schwerter
        order: 20
        lore:
            - Click here to get sword for attacking your enemies
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 8
              reward:
                item: 280
                amount: 1
                enchants:
                    19: 1
            - item1:
                item: IRON_INGOT
                amount: 1
              reward:
                item: 283
                amount: 1
                enchants:
                    16: 1
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 283
                amount: 1
                enchants:
                    16: 2
            - item1:
                item: IRON_INGOT
                amount: 7
              reward:
                item: 283
                amount: 1
                enchants:
                    16: 3
            - item1:
                item: GOLD_INGOT
                amount: 3
              reward:
                item: 267
                amount: 1
                enchants:
                    16: 2
                    19: 1
            - item1:
                item: GOLD_INGOT
                amount: 15
              reward:
                name: Axt der Unendlichkeit
                namecolor: GOLD
                item: 286
                amount: 1
                enchants:
                    34: 1
                    16: 1
                    19: 1
    bows:
        item: 261
        name: Bögen
        order: 30
        lore:
            - Prove yourself as a marksman with these wonderful bows
        offers:
            - item1:
                item: GOLD_INGOT
                amount: 3
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
            - item1:
                item: GOLD_INGOT
                amount: 7
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
                    48: 1
            - item1:
                item: GOLD_INGOT
                amount: 13
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
                    48: 2
            - item1:
                item: GOLD_INGOT
                amount: 16
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
                    50: 1
            - item1:
                item: GOLD_INGOT
                amount: 15
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
                    50: 1
                    49: 1
            - item1:
                item: GOLD_INGOT
                amount:
              reward:
                item: 262
                amount: 1
    eat:
        item: GRILLED_PORK
        name: Essen
        order: 40
        lore:
            - Are you hungry? Get something to eat.
        offers: 
            - item1:
                item: CLAY_BRICK
                amount: 4
              reward:
                item: GRILLED_PORK
                amount: 2
            - item1:
                item: IRON_INGOT
                amount: 2
              reward:
                item: 322
                amount: 1
            - item1:
                item: GOLD_INGOT
                amount: 5
              reward:
                item: 297
                amount: 10
    pickaxes:
        item: DIAMOND_PICKAXE
        name: Spitzhacken
        order: 50
        lore:
            - Destroy others blocks? Use these pickaxes.
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 4
              reward:
                item: IRON_PICKAXE
                amount: 1
                enchants:
                    35: 1
            - item1:
                item: IRON_INGOT
                amount: 2
              reward:
                item: IRON_PICKAXE
                amount: 1
                enchants:
                    35: 2
            - item1:
                item: GOLD_INGOT
                amount: 1
              reward:
                item: IRON_PICKAXE
                amount: 1
                enchants:
                    35: 3
    blocks:
        item: SANDSTONE
        name: Blöcke
        order: 60
        lore:
            - Get to the others! Possible with blocks.
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: 24
                meta: 2
                amount: 2
            - item1:
                item: CLAY_BRICK
                amount: 7
              reward:
                item: 121
                amount: 1
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 42
                amount: 1
            - item1:
                item: CLAY_BRICK
                amount: 15
              reward:
                item: 89
                amount: 4
            - item1:
                item: CLAY_BRICK
                amount: 4
              reward:
                item: 20
                amount: 1
    usefulstuff:
        item: TNT
        name: Nützliche Sachen
        order: 70
        lore:
            - Looking for useful stuff? Here are some!
        offers:
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: TNT
                amount: 1
            - item1:
                item: GOLD_INGOT
                amount: 1
              reward:
                item: 259
                amount: 1
            - item1:
                item: IRON_INGOT
                amount: 1
              reward:
                item: 54
                amount: 1
    drinks:
        item: POTION
        name: Tränke
        order: 80
        lore:
            - Not enough? Use these potions and you'll feel better!
        offers:
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 373
                amount: 1
                meta: 8197
            - item1:
                item: IRON_INGOT
                amount: 5
              reward:
                item: 373
                amount: 1
                meta: 8229
            - item1:
                item: IRON_INGOT
                amount: 7
              reward:
                item: 373
                amount: 1
                meta: 8194
            - item1:
                item: GOLD_INGOT
                amount: 1
              reward:
                item: 373
                amount: 1
                meta: 8201
            - item1:
                item: GOLD_INGOT
                amount: 3
              reward:
                item: 373
                amount: 1
                meta: 8193
                